### ISSUE TITLE
might want to have ignoreRelations

### ISSUE THREAD

**Issue by cebe** [yiiext/activerecord-relation-behavior#8]
might want to have ignoreRelations as in http://code.google.com/p/yii-user-management/source/browse/trunk/user/components/CAdvancedArBehavior.php#84

**Comment by ckristo** [comment]
in contrast to CAdvancedArBehavior's ignoreRelations it's not possible to configure a default set of relations to ignore on save(), right? (you always have to specify them using the scopes described above)

**Comment by cebe** [comment]
correct, this is currently not possible.

**Comment by ckristo** [comment]
ok .. as I see it, this wouldn't be hard to integrate / implement .. should I prepare a pull request?

**Comment by cebe** [comment]
sure, go ahead :)

**Comment by ckristo** [comment]
Done -- see pull request https://github.com/yiiext/activerecord-relation-behavior/pull/53 -- I hope that the implementation suites you fine.. I've implemented tests for withRelations() and withoutRelations() as well -- but didn't test combinations because my implementation shouldn't interfere with the scope functions at all...

**Comment by ckristo** [comment]
Done -- see pull request https://github.com/yiiext/activerecord-relation-behavior/pull/54 -- I hope that the implementation suites you fine.. I've implemented tests for withRelations() and withoutRelations() as well -- but didn't test combinations because my implementation shouldn't interfere with the scope functions at all...
